RESTAURANTS = [
    {
        "id": "vidyarthi-bhavan",
        "name": "Vidyarthi Bhavan",
        "cuisine": "South Indian",
        "area": "Basavanagudi",
        "price": "$",
        "rating": 4.6,
        "distance_km": 4.8,
        "open_now": True,
        "address": "Gandhi Bazaar, Basavanagudi, Bengaluru",
        "phone": "-",
        "hours": "6:30 AM - 11:30 AM, 2:00 PM - 8:00 PM",
        "tags": ["dosa", "breakfast", "heritage", "vegetarian"],
        "description": "A Bengaluru institution known for crisp masala dosa, quick service, and old-school breakfast energy.",
        "image": "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=1200&q=80",
        "maps_url": "",
    },
    {
        "id": "mtr-lalbagh-road",
        "name": "MTR",
        "cuisine": "South Indian",
        "area": "Lalbagh Road",
        "price": "$$",
        "rating": 4.5,
        "distance_km": 3.9,
        "open_now": True,
        "address": "Lalbagh Road, Bengaluru",
        "phone": "-",
        "hours": "6:30 AM - 11:00 AM, 12:30 PM - 9:00 PM",
        "tags": ["thali", "dosa", "filter coffee", "vegetarian"],
        "description": "Classic Bengaluru meals, rava idli, strong filter coffee, and a dining room built around tradition.",
        "image": "https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=1200&q=80",
        "maps_url": "",
    },
    {
        "id": "nagarjuna-residency-road",
        "name": "Nagarjuna",
        "cuisine": "Andhra",
        "area": "Residency Road",
        "price": "$$",
        "rating": 4.4,
        "distance_km": 2.1,
        "open_now": True,
        "address": "Residency Road, Bengaluru",
        "phone": "-",
        "hours": "12:00 PM - 11:00 PM",
        "tags": ["andhra meals", "biryani", "spicy", "family"],
        "description": "Banana-leaf Andhra meals, fiery sides, biryani, and the kind of lunch rush that moves fast.",
        "image": "https://images.unsplash.com/photo-1563379091339-03246963d51a?auto=format&fit=crop&w=1200&q=80",
        "maps_url": "",
    },
    {
        "id": "meghana-foods-koramangala",
        "name": "Meghana Foods",
        "cuisine": "Andhra Biryani",
        "area": "Koramangala",
        "price": "$$",
        "rating": 4.5,
        "distance_km": 5.8,
        "open_now": True,
        "address": "Koramangala, Bengaluru",
        "phone": "-",
        "hours": "11:30 AM - 1:00 AM",
        "tags": ["biryani", "delivery", "spicy", "late night"],
        "description": "Bengaluru's comfort-order favorite for fragrant biryani, generous portions, and late-night cravings.",
        "image": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=1200&q=80",
        "maps_url": "",
    },
    {
        "id": "ctr-malleshwaram",
        "name": "CTR",
        "cuisine": "South Indian",
        "area": "Malleshwaram",
        "price": "$",
        "rating": 4.6,
        "distance_km": 6.2,
        "open_now": False,
        "address": "Malleshwaram, Bengaluru",
        "phone": "-",
        "hours": "7:30 AM - 12:30 PM, 4:00 PM - 9:00 PM",
        "tags": ["benne dosa", "breakfast", "filter coffee", "vegetarian"],
        "description": "A beloved stop for buttery benne dosa, compact tables, and a steady stream of regulars.",
        "image": "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=1200&q=80",
        "maps_url": "",
    },
    {
        "id": "karavalli",
        "name": "Karavalli",
        "cuisine": "Coastal Indian",
        "area": "Ashok Nagar",
        "price": "$$$",
        "rating": 4.7,
        "distance_km": 1.8,
        "open_now": True,
        "address": "Ashok Nagar, Bengaluru",
        "phone": "-",
        "hours": "12:30 PM - 3:00 PM, 7:00 PM - 11:00 PM",
        "tags": ["seafood", "coastal", "date night", "special occasion"],
        "description": "A refined coastal Indian restaurant with polished service, seafood curries, appams, and regional plates.",
        "image": "https://images.unsplash.com/photo-1579631542720-3a87824fff86?auto=format&fit=crop&w=1200&q=80",
        "maps_url": "",
    },
    {
        "id": "sattvam-sadashivanagar",
        "name": "Sattvam",
        "cuisine": "North Indian",
        "area": "Sadashivanagar",
        "price": "$$$",
        "rating": 4.4,
        "distance_km": 6.7,
        "open_now": True,
        "address": "Sadashivanagar, Bengaluru",
        "phone": "-",
        "hours": "12:00 PM - 3:30 PM, 7:00 PM - 10:30 PM",
        "tags": ["buffet", "vegetarian", "family", "north indian"],
        "description": "A vegetarian buffet-style restaurant for North Indian classics, chaats, desserts, and family meals.",
        "image": "https://images.unsplash.com/photo-1618449840665-9ed506d73a34?auto=format&fit=crop&w=1200&q=80",
        "maps_url": "",
    },
    {
        "id": "toit-indiranagar",
        "name": "Toit",
        "cuisine": "Indian Pub Food",
        "area": "Indiranagar",
        "price": "$$$",
        "rating": 4.5,
        "distance_km": 4.6,
        "open_now": True,
        "address": "Indiranagar, Bengaluru",
        "phone": "-",
        "hours": "12:00 PM - 1:00 AM",
        "tags": ["pub", "groups", "late night", "casual"],
        "description": "A lively Indiranagar crowd-puller with Indian comfort bites, pizzas, and group-friendly seating.",
        "image": "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80",
        "maps_url": "",
    },
    {
        "id": "hallimane-malleshwaram",
        "name": "Hallimane",
        "cuisine": "Kannadiga",
        "area": "Malleshwaram",
        "price": "$$",
        "rating": 4.2,
        "distance_km": 6.4,
        "open_now": True,
        "address": "Malleshwaram, Bengaluru",
        "phone": "-",
        "hours": "7:00 AM - 10:30 PM",
        "tags": ["karnataka meals", "ragi mudde", "breakfast", "vegetarian"],
        "description": "Kannadiga-style meals, snacks, and regional comfort food in an easygoing dining room.",
        "image": "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=80",
        "maps_url": "",
    },
    {
        "id": "shivaji-military-hotel",
        "name": "Shivaji Military Hotel",
        "cuisine": "Donne Biryani",
        "area": "Jayanagar",
        "price": "$$",
        "rating": 4.3,
        "distance_km": 7.2,
        "open_now": False,
        "address": "Jayanagar, Bengaluru",
        "phone": "-",
        "hours": "8:30 AM - 3:30 PM",
        "tags": ["donne biryani", "non vegetarian", "local favorite", "lunch"],
        "description": "An old-school Bengaluru favorite for donne biryani and meat dishes served without fuss.",
        "image": "https://images.unsplash.com/photo-1599043513900-ed6fe01d3833?auto=format&fit=crop&w=1200&q=80",
        "maps_url": "",
    },
]


def all_cuisines():
    return sorted({restaurant["cuisine"] for restaurant in RESTAURANTS})


def all_areas():
    return sorted({restaurant["area"] for restaurant in RESTAURANTS})


def all_tags():
    tags = set()
    for restaurant in RESTAURANTS:
        tags.update(restaurant["tags"])
    return sorted(tags)
